### ISSUE TITLE
"aspect" is not a setting

### ISSUE THREAD

**Issue by xkryptor** [jeremysanders/veusz#100]
I had certain Veusz files, after a fresh install of Ubuntu and later Veusz, when I open those files this is the error message I get:

	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/veusz/windows/mainwindow.py", line 1081, in openFileInWindow
	    exec script in env
	  File "<string>", line 12028, in <module>
	  File "/usr/lib/python2.7/dist-packages/veusz/document/commandinterface.py", line 366, in Set
	    pref = self.currentwidget.prefLookup(var)
	  File "/usr/lib/python2.7/dist-packages/veusz/widgets/widget.py", line 226, in prefLookup
	    return obj.settings.getFromPath( parts[i:] )
	  File "/usr/lib/python2.7/dist-packages/veusz/setting/settings.py", line 202, in getFromPath
	    raise ValueError, '"%s" is not a setting' % name
	ValueError: "aspect" is not a setting

**Comment by jeremysanders** [comment]
Are you sure you're not loading the files in an older version of Veusz? Veusz doesn't support loading files from newer versions in older versions. You can look at the file in a text editor, which should show the version that created them.

**Comment by xkryptor** [comment]
My bad, the file was saved in version 1.20.1 and I installed Veusz with apt. I assumed it would install the latest version but installed 1.15. That explains it.

**Comment by jeremysanders** [comment]
Yes - it's pretty old in some Ubuntu versions. I think it's more up to date in the latest version.
