### ISSUE TITLE
support for NaN during if with minuit

### ISSUE THREAD

**Issue by jlec** [jeremysanders/veusz#105]
I am trying to fit a dataset for which I did set during import the "emtpy -> NaN" option. Could it be possible to neglect those values during the fitting to make minuit fitting work?

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/veusz/windows/consolewindow.py", line 249, in runFunction
    func()
  File "/usr/lib64/python2.7/site-packages/veusz/widgets/fit.py", line 367, in actionFit
    document.OperationMultiple(operations, descr=_('fit')) )
  File "/usr/lib64/python2.7/site-packages/veusz/document/doc.py", line 193, in applyOperation
    retn = operation.do(self)
  File "/usr/lib64/python2.7/site-packages/veusz/document/operations.py", line 1063, in do
    op.do(document)
  File "/usr/lib64/python2.7/site-packages/veusz/document/operations.py", line 72, in do
    setting.set(self.value)
  File "/usr/lib64/python2.7/site-packages/veusz/setting/setting.py", line 132, in set
    self._val = self.convertTo(v)
  File "/usr/lib64/python2.7/site-packages/veusz/setting/setting.py", line 559, in convertTo
    minval=self.minval, maxval=self.maxval)
  File "/usr/lib64/python2.7/site-packages/veusz/setting/setting.py", line 525, in _finiteRangeFloat
    raise utils.InvalidType('Finite values only allowed')
InvalidType: Finite values only allowed

**Comment by jeremysanders** [comment]
Thanks for the report. This should be fixed in the above commit.
