### ISSUE TITLE
Failed pdf export with veusz v1.22.99

### ISSUE THREAD

**Issue by brunetto** [jeremysanders/veusz#109]
Trying to export a .vsz file to pdf from the GUI I obtained the following error:

```
Veusz version: 1.22.99
Python version: 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2]
Python platform: linux
Numpy version: 1.8.2
Qt version: 5.2.1
PyQt version: 5.2.1
SIP version: 4.15.5
Date: Sat, 11 Apr 2015 23:01:00 +0000

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/veusz/dialogs/export.py", line 438, in accept
    _checkAndExport()
  File "/usr/local/lib/python3.4/dist-packages/veusz/dialogs/export.py", line 407, in _checkAndExport
    export.export()
  File "/usr/local/lib/python3.4/dist-packages/veusz/document/export.py", line 185, in export
    self.exportPDFOrPS(ext)
  File "/usr/local/lib/python3.4/dist-packages/veusz/document/export.py", line 322, in exportPDFOrPS
    text = scalePDFMediaBox(text, printer.width(), sizes)
  File "/usr/local/lib/python3.4/dist-packages/veusz/document/export.py", line 72, in scalePDFMediaBox
    outtext += text[outidx:match.start()] + newbox
TypeError: Can't convert 'bytes' object to str implicitly

Frame accept (File /usr/local/lib/python3.4/dist-packages/veusz/dialogs/export.py, line 438)
 cntrl = <PyQt5.QtWidgets.QComboBox object at 0x7f7dd626f828>
 pages = [0]
 pagecount = [0]
 filename = '/home/ziosi/Dropbox/Research/PhD_Mapelli/4-ParameterSpace/repo/Analysis/paperPlotsFreshStart/avgDBH.pdf'
 setdb = <veusz.setting.settingdb._SettingDB object at 0x7f7de2457438>
 _checkAndExport = <function ExportDialog.accept.<locals>._checkAndExport at 0x7f7dd5c2fe18>
 valid = 2
 setn = 'export_DPI_PDF'
 self = <veusz.dialogs.export.ExportDialog object at 0x7f7dd5c248b8>
  self.Accepted = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.Rejected = 0
  self.__dict__ = {'horizontalLayout_4': <PyQt5.QtWidgets.QHBoxLayout object at 0x7f7dd626fee8>, 'pageRangeMin': <PyQt5.QtWidgets.QSpinBox...
  self.__doc__ = 'Export dialog.'
  self.__module__ = 'veusz.dialogs.export'
  self.buttonBox = <PyQt5.QtWidgets.QDialogButtonBox object at 0x7f7dd6274048>
  self.buttonBrowse = <PyQt5.QtWidgets.QPushButton object at 0x7f7dd5c24e58>
  self.checkMultiPage = <PyQt5.QtWidgets.QCheckBox object at 0x7f7dd5c2aaf8>
  self.checkOverwrite = <PyQt5.QtWidgets.QCheckBox object at 0x7f7dd626fd38>
  self.dirname = '/home/ziosi/Dropbox/Research/PhD_Mapelli/4-ParameterSpace/repo/Analysis/paperPlotsFreshStart'
  self.document = <veusz.document.doc.Document object at 0x7f7dd72df5e8>
  self.editFileName = <PyQt5.QtWidgets.QLineEdit object at 0x7f7dd5c24dc8>
  self.exportAntialias = <PyQt5.QtWidgets.QCheckBox object at 0x7f7dd626f708>
  self.exportBackgroundButton = <PyQt5.QtWidgets.QPushButton object at 0x7f7dd626f948>
  self.exportColor = <PyQt5.QtWidgets.QComboBox object at 0x7f7dd626fb88>
  self.exportDPI = <PyQt5.QtWidgets.QComboBox object at 0x7f7dd626f678>
  self.exportDPIPDF = <PyQt5.QtWidgets.QComboBox object at 0x7f7dd626f828>
  self.exportQuality = <PyQt5.QtWidgets.QSpinBox object at 0x7f7dd626fa68>
  self.exportSVGTextAsText = <PyQt5.QtWidgets.QCheckBox object at 0x7f7dd626fca8>
  self.fmtradios = {'png': <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f1f8>, 'tiff': <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd...
  self.formatselected = 'pdf'
  self.gridLayout = <PyQt5.QtWidgets.QGridLayout object at 0x7f7dd5c2ad38>
  self.gridLayout_2 = <PyQt5.QtWidgets.QGridLayout object at 0x7f7dd626f168>
  self.gridLayout_3 = <PyQt5.QtWidgets.QGridLayout object at 0x7f7dd626f558>
  self.groupBox = <PyQt5.QtWidgets.QGroupBox object at 0x7f7dd5c2a798>
  self.groupBox_2 = <PyQt5.QtWidgets.QGroupBox object at 0x7f7dd5c2ab88>
  self.groupBox_3 = <PyQt5.QtWidgets.QGroupBox object at 0x7f7dd626f4c8>
  self.horizontalLayout = <PyQt5.QtWidgets.QHBoxLayout object at 0x7f7dd5c2a828>
  self.horizontalLayout_2 = <PyQt5.QtWidgets.QHBoxLayout object at 0x7f7dd5c24a68>
  self.horizontalLayout_3 = <PyQt5.QtWidgets.QHBoxLayout object at 0x7f7dd5c24c18>
  self.horizontalLayout_4 = <PyQt5.QtWidgets.QHBoxLayout object at 0x7f7dd626fee8>
  self.label = <PyQt5.QtWidgets.QLabel object at 0x7f7dd5c2a9d8>
  self.labelBackgroundButton = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626f8b8>
  self.labelCheckOverwrite = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626fdc8>
  self.labelColor = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626faf8>
  self.labelDPI = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626f5e8>
  self.labelDPIPDF = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626f798>
  self.labelQuality = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626f9d8>
  self.labelSVGTextAsText = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626fc18>
  self.labelStatus = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626ff78>
  self.label_2 = <PyQt5.QtWidgets.QLabel object at 0x7f7dd5c2aca8>
  self.label_3 = <PyQt5.QtWidgets.QLabel object at 0x7f7dd626f0d8>
  self.label_4 = <PyQt5.QtWidgets.QLabel object at 0x7f7dd5c24d38>
  self.mainwindow = <veusz.windows.mainwindow.MainWindow object at 0x7f7dd72df798>
  self.pageRangeMax = <PyQt5.QtWidgets.QSpinBox object at 0x7f7dd5c2aa68>
  self.pageRangeMin = <PyQt5.QtWidgets.QSpinBox object at 0x7f7dd5c2a948>
  self.pageselected = 'single'
  self.radioFormatBMP = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f288>
  self.radioFormatEMF = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f048>
  self.radioFormatEPS = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2adc8>
  self.radioFormatJPG = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f318>
  self.radioFormatPDF = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2aee8>
  self.radioFormatPNG = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f1f8>
  self.radioFormatPS = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2af78>
  self.radioFormatSVG = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2ae58>
  self.radioFormatTIFF = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f3a8>
  self.radioFormatXPM = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f438>
  self.radioPageAll = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2a708>
  self.radioPageRange = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2a8b8>
  self.radioPageSingle = <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd5c2a288>
  self.radiofmts = {<PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f318>: 'jpg', <PyQt5.QtWidgets.QRadioButton object at 0x7f7dd626f438>...
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x7f7dd627d828>
  self.verticalLayout = <PyQt5.QtWidgets.QVBoxLayout object at 0x7f7dd5c2a048>
  self.verticalLayout_2 = <PyQt5.QtWidgets.QVBoxLayout object at 0x7f7dd5c2ac18>
  self.verticalLayout_3 = <PyQt5.QtWidgets.QVBoxLayout object at 0x7f7dd5c24af8>
 _overwriteQuestion = <function ExportDialog.accept.<locals>._overwriteQuestion at 0x7f7dd6295e18>
 text = '150'
 export = <veusz.document.export.Export object at 0x7f7dd6268320>

Frame _checkAndExport (File /usr/local/lib/python3.4/dist-packages/veusz/dialogs/export.py, line 419)
 setdb = <veusz.setting.settingdb._SettingDB object at 0x7f7de2457438>
 _overwriteQuestion = <function ExportDialog.accept.<locals>._overwriteQuestion at 0x7f7dd6295e18>
 export = <veusz.document.export.Export object at 0x7f7dd6268320>
 self = <veusz.dialogs.export.ExportDialog object at 0x7f7dd5c248b8>
 pagecount = [0]

Frame export (File /usr/local/lib/python3.4/dist-packages/veusz/document/export.py, line 185)
 ext = '.pdf'
 self = <veusz.document.export.Export object at 0x7f7dd6268320>
  self.__dict__ = {'bitmapdpi': 100, 'filename': '/home/ziosi/Dropbox/Research/PhD_Mapelli/4-ParameterSpace/repo/Analysis/paperPlotsFreshS...
  self.__doc__ = 'Class to do the document exporting.\n    \n    This is split from document to make that class cleaner.\n    '
  self.__module__ = 'veusz.document.export'
  self.__weakref__ = None
  self.antialias = True
  self.backcolor = '#ffffff00'
  self.bitmapdpi = 100
  self.color = True
  self.doc = <veusz.document.doc.Document object at 0x7f7dd72df5e8>
  self.filename = '/home/ziosi/Dropbox/Research/PhD_Mapelli/4-ParameterSpace/repo/Analysis/paperPlotsFreshStart/avgDBH.pdf'
  self.formats = [(['bmp'], 'Windows bitmap'), (['eps'], 'Encapsulated Postscript'), (['ps'], 'Postscript'), (['jpg'], 'Jpeg bitmap'), ([...
  self.pagenumber = [0]
  self.pdfdpi = 150
  self.quality = 85
  self.svgtextastext = True

Frame exportPDFOrPS (File /usr/local/lib/python3.4/dist-packages/veusz/document/export.py, line 325)
 fin = <_io.BufferedReader name='/home/ziosi/Dropbox/Research/PhD_Mapelli/4-ParameterSpace/repo/Analysis/paperPlotsFreshStart/a...
 pages = [0]
 self = <veusz.document.export.Export object at 0x7f7dd6268320>
 tmpfile = '/home/ziosi/Dropbox/Research/PhD_Mapelli/4-ParameterSpace/repo/Analysis/paperPlotsFreshStart/avgDBH.pdf.tmp.538339'
 printer = <PyQt5.QtPrintSupport.QPrinter object at 0x7f7dd5bf6518>
 ext = '.pdf'
 text = b'%PDF-1.4\n1 0 obj\n<<\n/Title (\xfe\xff)\n/Creator (\xfe\xff\x00V\x00e\x00u\x00s\x00z\x00 \x001\x00.\x002\x002\x00.\x0...
 sizes = [(1181, 885)]

Frame scalePDFMediaBox (File /usr/local/lib/python3.4/dist-packages/veusz/document/export.py, line 72)
 outidx = 0
 newbox = b'/MediaBox [0 417 567 842]'
 widthfactor = 0.4798387096774194
 outtext = ''
 text = b'%PDF-1.4\n1 0 obj\n<<\n/Title (\xfe\xff)\n/Creator (\xfe\xff\x00V\x00e\x00u\x00s\x00z\x00 \x001\x00.\x002\x002\x00.\x0...
 box = [0.0, 0.0, 595.0, 842.0]
 reqdsizes = [(1181, 885)]
 match = <_sre.SRE_Match object; span=(414, 437), match=b'/MediaBox [0 0 595 842]'>
 size = (1181, 885)
 pagewidth = 1240
```

Moreover, when trying to report it the bug report didn't worked with error 

```
Failed to connect to error server to send report. Is your internet connected?
```

The internet connection is working fine.
The file was created with veusz v1.22 and with that version the export works fine.

**Comment by jeremysanders** [comment]
Thanks very much for the report. This is another case of not testing adequately with Python 3.
