### ISSUE TITLE
Clone command - missing encode (veusz 1.24 on python 3)

### ISSUE THREAD

**Issue by paul-the-noob** [jeremysanders/veusz#158]
Hi Jeremy,

Here's a more or less minimal example

    Python 3.5.2 (default, Nov 11 2016, 04:18:53) 
    [GCC 4.8.5] on linux                                                                    
    Type "help", "copyright", "credits" or "license" for more information.                  
    >>> import veusz.embed as ve
    >>> e = ve.Embedded()
    >>> p = e.Root.Add ('page'); gri = p.Add ('grid'); gra = gri.Add ('graph')            
    >>> gra2 = gra.Clone (gri)
    Traceback (most recent call last):                                                      
      File "<stdin>", line 1, in <module>                                                   
      File "/home/paul/.local/lib/python3.5/site-packages/veusz-1.24-py3.5-linux-x86_64.egg/veusz/embed.py", line 575, in Clone                                                    
        newname=newname)                                                                    
      File "/home/paul/.local/lib/python3.5/site-packages/veusz-1.24-py3.5-linux-x86_64.egg/veusz/embed.py", line 316, in runCommand                                               
        return self.sendCommand( (self.winno, cmd, args[1:], args2) )                       
      File "/home/paul/.local/lib/python3.5/site-packages/veusz-1.24-py3.5-linux-x86_64.egg/veusz/embed.py", line 309, in sendCommand                                              
        raise retobj                                                                        
    ValueError: invalid literal for int() with base 10: 'b"1\\ngraph\\n\'graph1\'\\n\'/page1/grid1/graph1\'\\n5\\nAdd(\'axis\', name=u\'x\', autoadd=False)\\nAdd(\'axis\', name=u\'y\', autoadd=False)\\nTo(u\'y\')\\nSet(\'direction\', u\'vertical\')\\nTo(\'            
    >>>                                                                                     

Please find below a trivial patch against 1.24. But be advised that I didn't really test whether it breaks anything.

Cheers,
Paul

P.S.: By the way. Thanks for veusz. I'm using it more or less for all my plotting needs. It's really impressive.

--- mime.py	2015-04-05 14:38:55.000000000 +0200
+++ mime-patched.py	2016-11-13 10:16:54.527299960 +0100
@@ -245,7 +245,7 @@
 
     def __init__(self, widget, newparent, newname):
         mime = generateWidgetsMime([widget])
-        mime = str(mime.data(widgetmime))
+        mime = str(mime.data(widgetmime), encoding='utf-8')
         OperationWidgetPaste.__init__(self, newparent, mime,
                                       newnames=[newname])

**Comment by jeremysanders** [comment]
Thanks very much for the report. I've fixed this for the next release.
