### ISSUE TITLE
can not create 2D dataset in 1.25 version

### ISSUE THREAD

**Issue by And0k** [jeremysanders/veusz#159]
In all my Veusz files I'm used to create 2D datasets "from expression based on existing 2D dataset". And now seems none of them works. So I remain on 1.24 version. Error window output:
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.qtwidgets.datasetbrowser", line 389, in refresh
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.qtwidgets.datasetbrowser", line 335, in makeGrpTreeTags
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.qtwidgets.datasetbrowser", line 281, in makeGrpTree
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.qtwidgets.datasetbrowser", line 61, in __init__
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.datasets.twod", line 155, in userSize
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.datasets.expression", line 601, in data
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.datasets.expression", line 642, in evalDataset
AttributeError: 'Document' object has no attribute 'evalDatasetExpression'

**Comment by jeremysanders** [comment]
Thanks for the report. This part of the code was rewritten and a bug was introduced. I've fixed it and added a self test to help ensure it doesn't happen again.

**Comment by jeremysanders** [comment]
This is fixed in the 1.25.1 release.
